pdfNames = """
1.pdf,2.pdf,3.pdf
"""
pdfNames2 = """
Aryavart By Vaidya Indra Deva 1963 Khamriyapul - Vaidya Indra Dev.pdf,
Ashtadhyayi By Brahma Datta  1964 Amritsar - Ramlal Kapoor Trust.pdf,
Ashtadhyayi By Panini 1890 Prayag - Shiva Dayal Sinha.pdf,
Ashtadhyayi Shukla Yajurveda Prathishakyayoh Mata Vimarsha By Vijay Pal 1983 Haryana - Vijay Pal.pdf,
Ashtadhyayi Vol-3 By Pandita Brahma Datta - Ramlal Kapoor Trust.pdf,
Ashtadhyayiya Bhashyam Vol-1 By dayananda Saraswati 1984 Ajmer - Vaidik yantralay.pdf,
Atha Vedanga Prakasa Vol-8 By Dayananda Saraswati 1960 Ajmer - Vaidik yantralay.pdf,
Atharva Veda Khanda-20 By Kshema Karan Das Trivedi 1920 Prayag - Shri Raja Rajeshwar.pdf,
Atharva Veda Samhita With The Commentary of Shankaracharya Vol-2 Edited By Shankar Pandurang 1895 Bombay - Government Central Book Depot.pdf,
Chromopathy By Dwaraka Nath Narang 1983 New Delhi - Ishwar Das Narang.pdf,
Fundamental Mysticism In Vedic Worship Or The Mysteries Of Vedic Daily Prayers By Abyudayananda Saraswati 1983 Benaras - Vedodaya Foundation.pdf,
Kaya Kalpa Yoga By Narendra Nath Shastri 1938 Lucknow - Saraswati Pustak Bhandar.pdf,
Maha Bhashyam Ch-4 By Patanjali 1889 Benaras - Kripa Ram Sharma.pdf,
Maha Bhashyam Ch-6 By Patanjali 1889 Benaras - Kripa Ram Sharma.pdf,
Maha Bhashyam Ch-7 By Patanjali 1889 Benaras - Kripa Ram Sharma.pdf,
Maha Bhashyam Navahnikam Unidentified Due To Missing Pages - Panini Kanya.pdf,
Maha Bhashyam Vol-3 With The Commentary Of Kayyata 1889 Benaras - Kripa Ram Sharma.pdf,
Maha Bhashyam Vol-7 By Sudyumna Acharya 2017 Haryana - Ramlal Kapoor Trust.pdf,
Maha Bhashyam With The Commentary Of Kayyata Benaras - Kripa Ram Sharma.pdf,
Nagiri Lipi By Braj Mohan 1968 Benaras - Shabdloka Prakashan.pdf,
Nunakhar vale Baba Sammohanand By Satyavrat Shastri 2005 Benaras - Shyamala Prakashan.pdf,
Paniniya Ashtakam Purvardham By Ganga Datta Shastri 1962 Jalandhar - Sat Dharma Pracharak Mandal.pdf,
Ram Kaleva Benaras - Prithvinath Bhargav.pdf,
Rigveda Anukramani With The Commentry Of Vijay Pal 1979 Sonipat - Yudhistar.pdf,
Rigveda Vol-9 Edited By Vishwa Bandhu 1964 Hoshiarpur - Vishweshvaranand Vaidik Sansthan.pdf,
Samaveda Shatakam Edited By Swami Achyutananda Saraswati Luthiyana - Shanti Ashram.pdf,
Shri Ram Janma Bhumi Ka Rakta Ranjita Itihas 1998 Ayodhya - Puja Prakashan.pdf,
Shukla Yajuh Pratishakhyam By Shrimati Indu Rastogi 1967 Benaras - Chaukhamba.pdf,
Sona Aur Khoon Vol-1 By Acharya Chatursen 1957 Delhi - Rajpal And Sons.pdf,
Vaidik Adhyatma Jyothi By Anubhavananda Saraswati 1969 New Delhi - Gyan Gyan.pdf,
Vaidik Vigyan Aur Bharatiya Sanskriti By Giridhar Sharma Chaturvedi 1972 Patna - Bihar Rashtra Basha Parishad.pdf,
Vaidika Karma Vidhi By Prakasavati Bugga Shastri 1990 New Delhi - Prakasavati Bugga Shastri.pdf,
Varnochharana Shiksha By Dayananda Saraswati 1950 Ajmer - Vaidika Yantralay.pdf,
Vayakarana Bhushana Sara By kounda Bhatta Edited By Pandit Taranatha 1872 Calcutta - Ganesha Press.pdf,
Ved Sarvasva Vol-1 By Hari Prasad Vaidika Muni 1916 Delhi - Sat Dharma Pracharak Mandal.pdf,
Veda Adhyayan Vol-1 By Ram Prasad 1995 Jwalapur - Shraddha Sahitya Prakashan.pdf,
Vyakarana Maha Bhashya Of Patanjali Vol-2 Edited By F. Kielhorn 1965 Poona - Bhandarkar Oriental Research Institute.pdf,
Vyakarana Maha Bhashyam Vol-2 Edited By Veda Vrat 1963 Rohtak - Haryana Sahitya sansthan.pdf,
Vyakarana Maha Bhashyam Vol-2 Rohtak - Haryana Sahitya Sansthan.pdf,
Vyakarana Maha Bhashyam with The Commentary Of Kayyata Vol-4 1963 Rohtak - Haryana Sahitya Sansthan.pdf,
Vyakarana Mahabhashya With Kaiyatas Pradipa Vol-3 By Raghunath Kashinth Shastri 1937 Bombay - Nirnay Sagar Press.pdf,
Yajurveda Uttarardha - Vajasaneya Samhita Benaras - Gaurish Press.pdf """

